# Site settings
title: Mayank Saxena
description: 'Programmer • Developer • Tech Enthusiast'
url: 'https://github.com/mayank26saxena/mayank26saxena.github.io/'
baseurl: 'http://mayank26saxena.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mayank Saxena'
  email: mayank26saxena@gmail.com
  twitter_username: mayank_saxena96
  facebook_username: mayank96saxena
  github_username:  mayank26saxena
  linkedin_username:  mayank26saxena

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
